/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module addSubtract_21 (
    input [7:0] a,
    input [7:0] b,
    input alufn0,
    output reg [7:0] out,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [7:0] xb;
  
  reg [7:0] s;
  
  integer x;
  
  always @* begin
    for (x = 1'h0; x < 4'h8; x = x + 1) begin
      xb[(x)*1+0-:1] = b[(x)*1+0-:1] ^ alufn0;
    end
    s = a + xb + alufn0;
    out = s;
    z = s == 8'h00;
    n = s[7+0-:1];
    v = (a[7+0-:1] & xb[7+0-:1] & (~s[7+0-:1])) ^ ((~a[7+0-:1]) & (~xb[7+0-:1]) & (s[7+0-:1]));
  end
endmodule
