/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module blinker_26 (
    input clk,
    input rst,
    output reg led
  );
  
  
  
  reg [24:0] M_blink_d, M_blink_q = 1'h0;
  
  always @* begin
    M_blink_d = M_blink_q;
    
    M_blink_d = M_blink_q + 1'h1;
    led = M_blink_q[24+0-:1];
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_blink_q <= 1'h0;
    end else begin
      M_blink_q <= M_blink_d;
    end
  end
  
endmodule
