/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module rng_3 (
    input clk,
    input rst,
    output reg [2:0] out
  );
  
  
  
  wire [32-1:0] M_pn_gen_num;
  reg [1-1:0] M_pn_gen_next;
  reg [32-1:0] M_pn_gen_seed;
  pn_gen_14 pn_gen (
    .clk(clk),
    .rst(rst),
    .next(M_pn_gen_next),
    .seed(M_pn_gen_seed),
    .num(M_pn_gen_num)
  );
  
  reg [2:0] randNum;
  
  always @* begin
    M_pn_gen_seed = 1'h0;
    M_pn_gen_next = 1'h1;
    randNum = M_pn_gen_num[0+2-:3];
    out = randNum;
    if (randNum[2+0-:1] == 1'h1) begin
      if (randNum[0+1-:2] == 2'h0) begin
        out[2+0-:1] = 1'h1;
      end else begin
        out[2+0-:1] = 1'h0;
      end
    end
    if (randNum == 3'h0) begin
      out = 3'h4;
    end
  end
endmodule
