/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module btn_4 (
    input clk,
    input rst,
    input r,
    input p,
    input s,
    input be,
    output reg [1:0] c
  );
  
  
  
  reg M_rck_d, M_rck_q = 1'h0;
  reg M_scr_d, M_scr_q = 1'h0;
  reg M_ppr_d, M_ppr_q = 1'h0;
  
  always @* begin
    M_scr_d = M_scr_q;
    M_rck_d = M_rck_q;
    M_ppr_d = M_ppr_q;
    
    M_rck_d = r & be | M_rck_q;
    M_scr_d = s & be | M_scr_q;
    M_ppr_d = p & be | M_ppr_q;
    c[0+0-:1] = M_rck_q | M_ppr_q;
    c[1+0-:1] = M_scr_q | M_ppr_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_rck_q <= 1'h0;
      M_scr_q <= 1'h0;
      M_ppr_q <= 1'h0;
    end else begin
      M_rck_q <= M_rck_d;
      M_scr_q <= M_scr_d;
      M_ppr_q <= M_ppr_d;
    end
  end
  
endmodule
